name: kkma
version: 1.0.2+54

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  dio: ^5.7.0
  pinput: ^5.0.0
  shared_preferences: ^2.3.4
  awesome_dialog: ^3.2.1
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_native_splash: ^2.4.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_native_splash:
  color: "#0E486D"
#  image: assets/images/splash.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

  android_12:
#    image: assets/images/splash.png
    color: "#0E486D"
#    icon_background_color: "#0E486D"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Thin.ttf
          weight: 300
        - asset: assets/fonts/Alexandria-Regular.ttf
          weight: 400
        - asset: assets/fonts/Alexandria-Medium.ttf
          weight: 500
        - asset: assets/fonts/Alexandria-Bold.ttf
          weight: 700